## np.sort

return a sorted copy of an array

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([67, 10, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 7, 30, 67, 42],
       [69, 59, 78, 81],
       [22, 81, 39, 39],
       [54,  4, 80, 21],
       [26, 74, 36, 64],
       [31, 55, 21, 49]])

In [3]:
np.sort(a)    # for descending order use this[::-1]

array([ 5,  5, 10, 24, 36, 50, 52, 59, 61, 66, 67, 73, 73, 83, 87])

In [4]:
np.sort(b,axis=0)  # axis=0 is used for columne sort

array([[ 7,  4, 21, 21],
       [22, 30, 36, 39],
       [26, 55, 39, 42],
       [31, 59, 67, 49],
       [54, 74, 78, 64],
       [69, 81, 80, 81]])

## np.append

The numpy.append()appends values along the mentioned axis at the end of the array

In [5]:
 np.append(a,200)

array([ 67,  10,  36,   5,  73,  73,   5,  24,  66,  87,  61,  52,  83,
        59,  50, 200])

In [6]:
b

array([[ 7, 30, 67, 42],
       [69, 59, 78, 81],
       [22, 81, 39, 39],
       [54,  4, 80, 21],
       [26, 74, 36, 64],
       [31, 55, 21, 49]])

In [7]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 7., 30., 67., 42.,  1.],
       [69., 59., 78., 81.,  1.],
       [22., 81., 39., 39.,  1.],
       [54.,  4., 80., 21.,  1.],
       [26., 74., 36., 64.,  1.],
       [31., 55., 21., 49.,  1.]])

## np.concatenate

numpy.concatenate()function concatenate a sequence of array along an existing axis.

In [8]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## np.unique 

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [10]:
e = np.array([1,1,1,2,3,3,2,4,5,6,4,3,5,6,7,1])

In [11]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

## np.expand_dims

With the help of NumPy.expend_dims() method, we can get the expanded dimensions of an array

In [12]:
print(a)
a.shape

[67 10 36  5 73 73  5 24 66 87 61 52 83 59 50]


(15,)

In [13]:
print(np.expand_dims(a,axis=0))
np.expand_dims(a,axis=0).shape

[[67 10 36  5 73 73  5 24 66 87 61 52 83 59 50]]


(1, 15)

## np.where

The numpy.where() function returns the indices of elements in an input array where the give condition is satisfied

In [14]:
a

array([67, 10, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [15]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  4,  5,  8,  9, 10, 11, 12, 13], dtype=int64),)

In [16]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 10, 36,  5,  0,  0,  5, 24,  0,  0,  0,  0,  0,  0, 50])

In [17]:
np.where(a%2==0,0,a)

array([67,  0,  0,  5, 73, 73,  5,  0,  0, 87, 61,  0, 83, 59,  0])

# np.argmax

The numpy.argmax() function return indices of the max element of the array in a paticular axis

In [18]:
a

array([67, 10, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [19]:
np.argmax(a)

9

In [20]:
b

array([[ 7, 30, 67, 42],
       [69, 59, 78, 81],
       [22, 81, 39, 39],
       [54,  4, 80, 21],
       [26, 74, 36, 64],
       [31, 55, 21, 49]])

In [21]:
np.argmax(b,axis=0)

array([1, 2, 3, 1], dtype=int64)

In [22]:
# np.argmin
np.argmin(a)

3

In [23]:
np.argmin(b,axis=0)

array([0, 3, 5, 3], dtype=int64)

## np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a give axis.

In [24]:
a

array([67, 10, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [25]:
np.cumsum(a)

array([ 67,  77, 113, 118, 191, 264, 269, 293, 359, 446, 507, 559, 642,
       701, 751])

In [26]:
b

array([[ 7, 30, 67, 42],
       [69, 59, 78, 81],
       [22, 81, 39, 39],
       [54,  4, 80, 21],
       [26, 74, 36, 64],
       [31, 55, 21, 49]])

In [27]:
np.cumsum(b,axis=0)

array([[  7,  30,  67,  42],
       [ 76,  89, 145, 123],
       [ 98, 170, 184, 162],
       [152, 174, 264, 183],
       [178, 248, 300, 247],
       [209, 303, 321, 296]])

In [28]:
np.cumprod(a) #use for product

array([         67,         670,       24120,      120600,     8803800,
         642677400, -1081580296,  -188123328,   468762240,  2127609216,
         935143296,  1382811136, -1190792704, -1537292800,   444771328])

## np.percentile

numpy.percentile() function used to compute the nth percentile of the given data(array elements) along the specified axis.

In [29]:
a

array([67, 10, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [30]:
np.percentile(a,100) # percentage of maximun number

87.0

In [31]:
np.percentile(a,0) # percentage of minimum number

5.0

In [32]:
np.percentile(a,50) # percentage of middle term

59.0

In [33]:
np.median(a)

59.0

## np.histogram

NumPy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form 

In [36]:
a

array([67, 10, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [37]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 1, 1, 1, 0, 3, 3, 2, 2, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [38]:
np.histogram(a,bins=[0,50,100])

(array([ 5, 10], dtype=int64), array([  0,  50, 100]))

## np.corrcoef

Return Pearson product-moment correlation coefficient

In [39]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [40]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having
different elements with different sizes.

In [41]:
a

array([67, 10, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [42]:
items=[10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False,  True])

## np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [43]:
a

array([67, 10, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [44]:
np.flip(a)

array([50, 59, 83, 52, 61, 87, 66, 24,  5, 73, 73,  5, 36, 10, 67])

In [45]:
b

array([[ 7, 30, 67, 42],
       [69, 59, 78, 81],
       [22, 81, 39, 39],
       [54,  4, 80, 21],
       [26, 74, 36, 64],
       [31, 55, 21, 49]])

In [47]:
np.flip(b,axis=0)

array([[31, 55, 21, 49],
       [26, 74, 36, 64],
       [54,  4, 80, 21],
       [22, 81, 39, 39],
       [69, 59, 78, 81],
       [ 7, 30, 67, 42]])

## np.put

The numpy.put() function replace specific elements of an array with given values of p_array. Array indexed works on flattened
array.

In [51]:
a

array([70, 15, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [50]:
np.put(a,[0,1],[70,15])

## np.delete

The numpy.delete() function return a new array with the deletion of sub-array along with the mentioned axis

In [52]:
a

array([70, 15, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [53]:
np.delete(a,0)

array([15, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [55]:
np.delete(a,[0,2,6])

array([15,  5, 73, 73, 24, 66, 87, 61, 52, 83, 59, 50])

## Set functions

1.np.union1d

2.np.intersect1d

3.np.setdiff1d

4.np.setxor1d

5.np.in1d

In [56]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
np.intersect1d(m,n)

array([3, 4, 5])

In [60]:
np.setdiff1d(m,n)


array([1, 2])

## np.clip
numpy.clip()function is used to clip (limit) the values in an array.

In [61]:
a

array([70, 15, 36,  5, 73, 73,  5, 24, 66, 87, 61, 52, 83, 59, 50])

In [63]:
np.clip(a,a_min=15,a_max=66)

array([66, 15, 36, 15, 66, 66, 15, 24, 66, 66, 61, 52, 66, 59, 50])

In [64]:
# 17. np.swapaxes

In [65]:
# 18. np.uniform

In [66]:
# 19. np.count_nonzero

In [67]:
# 21. np.tile

In [68]:
# 22. np.repeat

In [69]:
# 25. np.allclose and equals