# Creating Numpy Arrays

In [5]:
# np.array
import numpy as np


a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [7]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
c = np.array([[[1,2],[4,5]],[[7,8],[3,9]]])
print(c)

[[[1 2]
  [4 5]]

 [[7 8]
  [3 9]]]


In [13]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
# dtype    (it is for change a data type)
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
# np.arange
np.arange(1,11,2)  # strides ,2 create alternate array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
# np.ones and np.zeros
np.ones((3,4))    # np.ones use to initialize values

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# np.random 
np.random.random((3,4))

array([[0.51290558, 0.73608052, 0.28911339, 0.13830487],
       [0.46123238, 0.66604052, 0.27942612, 0.84770679],
       [0.76266719, 0.80687856, 0.93954592, 0.79240715]])

In [22]:
# np.linspace
np.linspace(-10,10,10)   # Linearly saprable is used to sapret points with equal interval or equal distance b/w them

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [28]:
a1 = np.arange(10)    # vector 1D
a2 = np.arange(12,dtype=float).reshape(3,4)  # Metrics 2D
a3 = np.arange(8).reshape(2,2,2) # Tensor 3D
print(a1)
print('---------------------------')
print(a2)
print('---------------------------')
print(a3)

[0 1 2 3 4 5 6 7 8 9]
---------------------------
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
---------------------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [31]:
# ndim  -------------> it used for know the dimenson of array
a3.ndim

3

In [41]:
# shape
print(a3.shape) 
print('first 2 show the total number of 2d array (next 2s shows the number of row and column in this 2d array)')

(2, 2, 2)
first 2 show the total number of 2d array (next 2s shows the number of row and column in this 2d array)


In [43]:
# size
print('Total number of items in a3')
a3.size

Total number of items in a3


8

In [48]:
# itemsize -------> itemsize use to show every item how much memory size is occupy
a3.itemsize  # int32 take 4bits , int64 take 8 bits


4

In [49]:
# dtype ----> it is used for know the data type
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype

In [58]:
# astype  -------> use to change a data type
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Array Operations

In [59]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
# scalar operations
# arithmatics
print(a1)
a1 * 2    # a1 is a matrics and 2 is scaler

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [63]:
# realtional
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [67]:
# vector operations 
# arithmetic
a2 + a1

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Function

In [70]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[66., 18., 69.],
       [51., 49., 58.],
       [ 3., 61., 15.]])

In [81]:
# max/min/sum/prod
print(('maximum value =') ,np.max(a1))
print(('minimum value ='),np.min(a1))
print(('sum of value ='),np.sum(a1))
print(('product of number ='),np.prod(a1))

maximum value = 69.0
minimum value = 3.0
sum of value = 390.0
product of number = 32613854537880.0


In [84]:
# 0 --> column and 1 --> row
np.min(a1,axis=1)

array([18., 49.,  3.])

In [87]:
#mean/median/std/var
np.mean(a1,axis=0)

array([40.        , 42.66666667, 47.33333333])

In [88]:
# trignometric function
np.sin(a1)

array([[-0.02655115, -0.75098725, -0.11478481],
       [ 0.67022918, -0.95375265,  0.99287265],
       [ 0.14112001, -0.96611777,  0.65028784]])

In [90]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [92]:
# log and exponents
np.log(a1)

array([[4.18965474, 2.89037176, 4.2341065 ],
       [3.93182563, 3.8918203 , 4.06044301],
       [1.09861229, 4.11087386, 2.7080502 ]])

In [95]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[30., 18., 82.],
       [51., 84., 42.]])

# Indexing and Slicing

In [97]:
# indexing and Slicing is used for data fatching

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [102]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
a2[1,1]

5

In [105]:
a2[2,2]

10

In [106]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [108]:
a3[0,1,0]

2

In [109]:
a3[0,1,1]

3

In [110]:
a3[1,1,1]

7

# Slicing

In [113]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
a1[2:5:2]

array([2, 4])

In [119]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
a2[0,:]

array([0, 1, 2, 3])

In [121]:
a2[:,2]

array([ 2,  6, 10])

In [122]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [123]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
a2[:2,2:]

array([[2, 3],
       [6, 7]])

In [130]:
a2[::2,::3 ]

array([[ 0,  3],
       [ 8, 11]])

In [131]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
a2[::2,1:4:2]  # a2[::2,1:4:2]

array([[ 1,  3],
       [ 9, 11]])

In [151]:
a2[1:2,::3]  # [1,::3]

array([[4, 7]])

In [152]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [154]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [156]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [159]:
 a3[0,1,:]

array([3, 4, 5])

In [160]:
a3[1,:,1]

array([10, 13, 16])

In [161]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [170]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [176]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [177]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [178]:
a3 

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [179]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [180]:
# reshape

In [183]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [185]:
# ravel  ----> convert any dimension data in 1D

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

## It is used to multiple data stacking of multiple data sources

In [187]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [189]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [191]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# spliting

## we splitit the data source from main data base (example college data base)

In [192]:
# horizontal spliting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [195]:
# vertical spliting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [196]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]